import { test, expect } from '@playwright/test';
const widths=[375,390,430,768,1024,1280,1440,1920];
for(const width of widths) test(`Responsive homepage at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:1000});await page.emulateMedia({reducedMotion:'reduce'});
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/');await expect(page.locator('h1')).toHaveCount(1);await expect(page.locator('h1')).toContainText('Braver Africa.');
 await page.locator('footer').scrollIntoViewIfNeeded();await page.waitForTimeout(200);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 for(const img of await page.locator('main img').all()){await img.scrollIntoViewIfNeeded();await expect(img).toHaveJSProperty('complete',true);expect(await img.evaluate((el:HTMLImageElement)=>el.naturalWidth)).toBeGreaterThan(0)}
 expect(errors).toEqual([]);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`docs/preview-${width}.png`,fullPage:true});
});
test('Menu traps focus, closes with Escape and restores focus',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');const button=page.getByRole('button',{name:'Open menu'});await button.click();const dialog=page.getByRole('dialog',{name:'Main menu'});await expect(dialog).toBeVisible();await expect(dialog.getByRole('link',{name:'01 Home'})).toBeVisible();await expect(dialog.getByRole('link',{name:'02 About'})).toBeVisible();expect(await page.evaluate(()=>document.body.style.overflow)).toBe('hidden');for(let i=0;i<15;i++){await page.keyboard.press('Tab');expect(await page.evaluate(()=>!!document.activeElement?.closest('dialog'))).toBeTruthy()}await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(button).toBeFocused();await button.click();await dialog.getByRole('link',{name:'03 Programmes'}).click();await expect(dialog).not.toBeVisible();await expect(page).toHaveURL(/\/programmes$/)});
test('Search and platform details',async({page})=>{await page.setViewportSize({width:1440,height:1000});await page.goto('/');await page.getByRole('button',{name:'Search the foundation'}).click();await page.getByRole('searchbox').fill('Feather Awards');await page.getByRole('dialog').getByRole('link',{name:'Feather Awards'}).click();await expect(page).toHaveURL(/\/feather-awards$/);await expect(page.locator('h1')).toContainText('VISIBLE.');await page.goto('/');await page.getByRole('button',{name:'Explore Fashion Stage'}).click();await expect(page.getByRole('dialog')).toContainText('Style is a language of possibility')});
test('Story chapters and local enquiry download',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Watch our story'}).click();await expect(page.getByRole('dialog')).toContainText('It starts with belonging.');await page.getByRole('button',{name:'Next chapter'}).click();await page.getByRole('button',{name:'Next chapter'}).click();await page.getByRole('button',{name:'Join the story'}).click();await page.getByLabel('Your name').fill('Test Visitor');await page.getByLabel('Email address').fill('visitor@example.com');await page.getByLabel('How would you like to be involved?').fill('I would like to volunteer.');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Save enquiry'}).click();expect((await download).suggestedFilename()).toBe('thami-dish-enquiry.txt');await expect(page.getByRole('status')).toContainText('Nothing has been submitted')});
test('Donation pledge clearly avoids claiming payment',async({page})=>{await page.goto('/');await page.locator('header').getByRole('button',{name:'Donate',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('no payment will be taken');await page.getByLabel('Your name').fill('Test Visitor');await page.getByLabel('Email address').fill('visitor@example.com');await page.getByLabel('Pledge amount (ZAR)').fill('250');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Save pledge'}).click();await download;await expect(page.getByRole('status')).toContainText('Your pledge is ready.')});

