import { useState } from 'react';
import { ArrowRight, Check, Download, Search } from 'lucide-react';
import { Dialog } from './Dialog';
import { SectionLabel } from './Primitives';
import { ecosystemPlatforms, navigationItems, type Platform } from '../../data/content';
export type Overlay = {type:'story'} | {type:'search'} | {type:'platform';platform:Platform} | {type:'involve';kind:string} | {type:'social';name:string} | null;
export function SiteOverlay({overlay,onClose,onChange}:{overlay:NonNullable<Overlay>;onClose:()=>void;onChange:(value:Overlay)=>void}) {
 const [query,setQuery]=useState(''); const [saved,setSaved]=useState(false); const [chapter,setChapter]=useState(0);
 if(overlay.type==='search') {const results: {title:string;href:string;description:string;platform?:Platform}[]=[...navigationItems.map(n=>({title:n.label,href:n.href,description:'Explore the foundation'})),...ecosystemPlatforms.filter(p=>p.id!=='awards').map(p=>({title:p.title,href:'#ecosystem',description:p.description,platform:p}))].filter(n=>(n.title+' '+n.description).toLowerCase().includes(query.toLowerCase()));return <Dialog title="Search the foundation" onClose={onClose}><SectionLabel>Find your way</SectionLabel><h2>What brings you here?</h2><label className="search-field"><Search size={22}/><input autoFocus type="search" aria-label="Search pages and platforms" placeholder="Search the foundation…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="search-results">{results.length?results.map(r=><a key={r.title} href={r.href} onClick={e=>{'platform' in r?(e.preventDefault(),onChange({type:'platform',platform:r.platform!})):onClose()}}>{r.title}<ArrowRight size={18}/></a>):<p>No results. Try “culture”, “impact” or “volunteer”.</p>}</div></Dialog>}
 if(overlay.type==='platform')return <Dialog title={overlay.platform.title} onClose={onClose}><img className="dialog-image" src={overlay.platform.image} alt={overlay.platform.alt}/><SectionLabel>Our ecosystem</SectionLabel><h2>{overlay.platform.title}</h2><p className="dialog-copy">{overlay.platform.detail}</p><button className="pill" onClick={()=>onChange({type:'involve',kind:'Partner'})}>Be part of it <ArrowRight size={18}/></button></Dialog>;
 if(overlay.type==='story'){const chapters=[{label:'01 / People',title:'It starts with belonging.',text:'Every young person deserves the freedom to become who they are. To be seen. To feel safe. To imagine a future of their own.'},{label:'02 / Purpose',title:'Possibility needs a place.',text:'Through education, advocacy, safe spaces, scholarships and community programmes, we support young LGBTQI+ people across Africa.'},{label:'03 / Change',title:'A future we build together.',text:'Culture opens conversations. Community turns them into change. Together, we can create a brighter, braver Africa.'}];return <Dialog title="Our story" onClose={onClose} className="story-dialog"><img className="dialog-image" src="/images/hero-foundation.webp" alt="A rainbow textile flowing behind a confident young person"/><SectionLabel>{chapters[chapter].label}</SectionLabel><h2>{chapters[chapter].title}</h2><p className="dialog-copy">{chapters[chapter].text}</p><div className="flex items-center justify-between"><div className="story-dots">{chapters.map((c,i)=><button key={c.label} aria-label={`Read chapter ${i+1}`} aria-pressed={chapter===i} onClick={()=>setChapter(i)}/>)}</div><button className="pill" onClick={()=>chapter<2?setChapter(chapter+1):onChange({type:'involve',kind:'Join'})}>{chapter<2?'Next chapter':'Join the story'}<ArrowRight size={18}/></button></div></Dialog>}
 if(overlay.type==='social')return <Dialog title={overlay.name} onClose={onClose}><SectionLabel>Stay connected</SectionLabel><h2>Find us on {overlay.name}.</h2><p className="dialog-copy">Our verified social links will be added here before launch. In the meantime, explore the people, purpose and platforms behind the foundation.</p><a className="pill" href="/#ecosystem" onClick={onClose}>Explore our platforms <ArrowRight size={18}/></a></Dialog>;
 return <Dialog title={`${overlay.kind} with the foundation`} onClose={onClose}><SectionLabel>Get involved / {overlay.kind}</SectionLabel><h2>{overlay.kind==='Donate'?'Make possibility possible.':overlay.kind==='Volunteer'?'Your time. Real change.':overlay.kind==='Partner'?'Greater impact, together.':'You belong here.'}</h2><p className="dialog-copy">{overlay.kind==='Donate'?'Thank you for wanting to support the foundation. Secure donations are not connected yet. You can prepare a pledge below; no payment will be taken.':'Tell us how you would like to get involved. This preview saves an enquiry to your device; it does not send or store your details on a server.'}</p>{saved?<div className="success-message rainbow-border" role="status"><Check/><h3>Your {overlay.kind==='Donate'?'pledge':'enquiry'} is ready.</h3><p>The text file has been downloaded to your device. Nothing has been submitted. Official contact details will be available before launch.</p><button className="text-link" onClick={()=>setSaved(false)}>Edit your details <ArrowRight size={16}/></button></div>:<form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const content=`Thami Dish Foundation — ${overlay.kind}\nName: ${data.get('name')}\nEmail: ${data.get('email')}\n${overlay.kind==='Donate'?'Pledge (ZAR): '+data.get('amount')+'\n':''}Message: ${data.get('message')}\n\nDraft only. Not submitted; no payment taken.`;const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='thami-dish-enquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setSaved(true)}} className="interest-form"><label>Your name<input name="name" autoComplete="name" required maxLength={100}/></label><label>Email address<input type="email" name="email" autoComplete="email" required maxLength={200}/></label>{overlay.kind==='Donate'&&<label>Pledge amount (ZAR)<input type="number" name="amount" min="1" max="10000000" step="1" required placeholder="250"/></label>}<label>{overlay.kind==='Donate'?'A note with your pledge (optional)':'How would you like to be involved?'}<textarea name="message" rows={3} maxLength={2000}/></label><button className="pill" type="submit">Save {overlay.kind==='Donate'?'pledge':'enquiry'} <Download size={16}/></button><p className="form-note">Saved only on your device. Not submitted.</p></form>}</Dialog>
}

